name: Spell Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@main
        with:
          config: cspell.json
